version: "1.0"
services:
  web1:
    build: .
    ports:
      - "8081:8080"
    image: "webapp"
  web2:
    build: .
    ports:
      - "8082:8080"
    image: "webapp"
  web3:
    build: .
    ports:
      - "8083:8080"
    image: "webapp"